name: DTGworks
favicon: null
layout_spectrum: 0.8050032372120768
typography_spectrum: 0.7349910959601402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6117846565321088
  lightness: 0.08966039516963065
  saturation: 0.26071724109351635
  rhythmicContrast: 0.009344355436041951
purpose: []
